spring:
  datasource:
    name: MultitenantDataSource
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:mem:multitenant
#    username: sa
#    password:
#    name: MultitenantPostegresDataSource
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/multi-tenant-kt-db}
    password: ${SPRING_DATASOURCE_USERNAME:password}
    username: ${SPRING_DATASOURCE_PASSWORD:postgres}
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      pool-name: algafoodPool
      connection-test-query: select now()
      maximum-pool-size: 5
      minimum-idle: 1
      connection-timeout: 20000
      idle-timeout: 10000
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
  jpa:
    database: postgreSQL
    show-sql: true